/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InterfaceRouteImport } from './routes/interface'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as ExtensibilityRouteImport } from './routes/extensibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as AppMIdRouteImport } from './routes/app.m.$id'
import { Route as AppDIdRouteImport } from './routes/app.d.$id'

const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InterfaceRoute = InterfaceRouteImport.update({
  id: '/interface',
  path: '/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensibilityRoute = ExtensibilityRouteImport.update({
  id: '/extensibility',
  path: '/extensibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LibraryRoute,
} as any)
const AppMIdRoute = AppMIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDIdRoute = AppDIdRouteImport.update({
  id: '/d/$id',
  path: '/d/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/extensibility': typeof ExtensibilityRoute
  '/intelligence': typeof IntelligenceRoute
  '/interface': typeof InterfaceRoute
  '/library': typeof LibraryRouteWithChildren
  '/migration': typeof MigrationRoute
  '/modules': typeof ModulesRoute
  '/performance': typeof PerformanceRoute
  '/risks': typeof RisksRoute
  '/roadmap': typeof RoadmapRoute
  '/simulation': typeof SimulationRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/app/': typeof AppIndexRoute
  '/app/d/$id': typeof AppDIdRoute
  '/app/m/$id': typeof AppMIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/extensibility': typeof ExtensibilityRoute
  '/intelligence': typeof IntelligenceRoute
  '/interface': typeof InterfaceRoute
  '/library': typeof LibraryRouteWithChildren
  '/migration': typeof MigrationRoute
  '/modules': typeof ModulesRoute
  '/performance': typeof PerformanceRoute
  '/risks': typeof RisksRoute
  '/roadmap': typeof RoadmapRoute
  '/simulation': typeof SimulationRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/app': typeof AppIndexRoute
  '/app/d/$id': typeof AppDIdRoute
  '/app/m/$id': typeof AppMIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/extensibility': typeof ExtensibilityRoute
  '/intelligence': typeof IntelligenceRoute
  '/interface': typeof InterfaceRoute
  '/library': typeof LibraryRouteWithChildren
  '/migration': typeof MigrationRoute
  '/modules': typeof ModulesRoute
  '/performance': typeof PerformanceRoute
  '/risks': typeof RisksRoute
  '/roadmap': typeof RoadmapRoute
  '/simulation': typeof SimulationRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/app/': typeof AppIndexRoute
  '/app/d/$id': typeof AppDIdRoute
  '/app/m/$id': typeof AppMIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/architecture'
    | '/auth'
    | '/extensibility'
    | '/intelligence'
    | '/interface'
    | '/library'
    | '/migration'
    | '/modules'
    | '/performance'
    | '/risks'
    | '/roadmap'
    | '/simulation'
    | '/library/$slug'
    | '/app/'
    | '/app/d/$id'
    | '/app/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/extensibility'
    | '/intelligence'
    | '/interface'
    | '/library'
    | '/migration'
    | '/modules'
    | '/performance'
    | '/risks'
    | '/roadmap'
    | '/simulation'
    | '/library/$slug'
    | '/app'
    | '/app/d/$id'
    | '/app/m/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/architecture'
    | '/auth'
    | '/extensibility'
    | '/intelligence'
    | '/interface'
    | '/library'
    | '/migration'
    | '/modules'
    | '/performance'
    | '/risks'
    | '/roadmap'
    | '/simulation'
    | '/library/$slug'
    | '/app/'
    | '/app/d/$id'
    | '/app/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  ExtensibilityRoute: typeof ExtensibilityRoute
  IntelligenceRoute: typeof IntelligenceRoute
  InterfaceRoute: typeof InterfaceRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  MigrationRoute: typeof MigrationRoute
  ModulesRoute: typeof ModulesRoute
  PerformanceRoute: typeof PerformanceRoute
  RisksRoute: typeof RisksRoute
  RoadmapRoute: typeof RoadmapRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interface': {
      id: '/interface'
      path: '/interface'
      fullPath: '/interface'
      preLoaderRoute: typeof InterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensibility': {
      id: '/extensibility'
      path: '/extensibility'
      fullPath: '/extensibility'
      preLoaderRoute: typeof ExtensibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/app/m/$id': {
      id: '/app/m/$id'
      path: '/m/$id'
      fullPath: '/app/m/$id'
      preLoaderRoute: typeof AppMIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/d/$id': {
      id: '/app/d/$id'
      path: '/d/$id'
      fullPath: '/app/d/$id'
      preLoaderRoute: typeof AppDIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDIdRoute: typeof AppDIdRoute
  AppMIdRoute: typeof AppMIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDIdRoute: AppDIdRoute,
  AppMIdRoute: AppMIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LibraryRouteChildren {
  LibrarySlugRoute: typeof LibrarySlugRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibrarySlugRoute: LibrarySlugRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  ExtensibilityRoute: ExtensibilityRoute,
  IntelligenceRoute: IntelligenceRoute,
  InterfaceRoute: InterfaceRoute,
  LibraryRoute: LibraryRouteWithChildren,
  MigrationRoute: MigrationRoute,
  ModulesRoute: ModulesRoute,
  PerformanceRoute: PerformanceRoute,
  RisksRoute: RisksRoute,
  RoadmapRoute: RoadmapRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
